version: '2'

services:

  go:
    build:
      dockerfile: dev/Dockerfile
      context: .
    image: dev_lake
    volumes:
      - ./dev/lifecycle:/opt/lifecycle
      - ./vendor/gopkg.in:/go/src/gopkg.in
      - ./vendor/golang.org:/go/src/golang.org
      - ./vendor/github.com/:/go/src/github.com/
      - .:/go/src/shadow/jancajthaml
      - ./src:/go/src/sparrow
    working_dir: /go/src/shadow/jancajthaml
    environment:
      - GOOS
      - GOARCH
      - GOPATH=/go
      - COMPOSE_PROJECT_NAME
    entrypoint: ["go"]
    privileged: true

  service:
    build:
      dockerfile: Dockerfile
      context: .
    image: lake
    restart: "no"
    ports:
      - "5562"
      - "5561"
    command: ["run"]

  sync:
    extends: go
    entrypoint: ["govendor"]
    command: ["sync", "-v"]

  fetch:
    extends: go
    entrypoint: ["govendor"]
    command: ["fetch", "github.com/spf13/viper"]

  lint:
    extends: go
    entrypoint: ["/opt/lifecycle/lint"]

  package:
    extends: go
    entrypoint: ["/opt/lifecycle/package"]

  test:
    extends: go
    command: ["test", "-v", "./src/...", "-benchmem", "-bench=."]
