name: Go

on: [push, pull_request]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        wget https://github.com/zeromq/libzmq/releases/download/v4.3.1/zeromq-4.3.1.tar.gz -O /tmp/zeromq.tar.gz
        tar -xzvf /tmp/zeromq.tar.gz -C /tmp && cd /tmp/zeromq-* && mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_CURVE=ON .. && make && sudo make install
        cd services/lake
        GO111MODULE=on go mod verify
        GO111MODULE=on go mod tidy
        GO111MODULE=on go mod vendor

    - name: Test
      run:  |
        cd services/lake
        go test -v ./... -timeout=10s

    - name: Benchmark
      run:  |
        cd services/lake
        go test -v -run=^$ -bench=. -benchmem -timeout=1m
